server:
  port: 8071
#xxl-job
# 执行器"AppName"和地址信息配置：AppName执行器心跳注册分组依据；地址信息用于"调度中心请求并触发任务"和"执行器注册"。
# 执行器默认端口为9999，执行器IP默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用。
#单机部署多个执行器时，注意要配置不同执行器端口
xxl:
  job:
    admin:
      addresses: http://8.135.112.184:8100/xxl-job-admin
    accessToken:
    executor:
      address: ''
      #      appname: xxl-job-executor-sample
      appname: xxl-job-executor-sample
      ip:
      port: 9999
      # 执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logpath:
      # xxl-job log retention days：执行器Log文件定期清理功能，指定日志保存天数，日志文件过期自动删除。
      #限制至少保持3天，否则功能不生效；
      logretentiondays: 3